package handler

import (
	"errors"
	"strings"
	"testing"
)

func TestCheckValidAlias(t *testing.T) {
	// ============================================================
	// TEST CASES ARE GENERATED BY Claude
	// ============================================================
	tests := []struct {
		name    string
		alias   string
		wantErr error
	}{
		{name: "valid short alias", alias: "abc123", wantErr: nil},
		{name: "valid single character", alias: "a", wantErr: nil},
		{name: "valid all lowercase", alias: "abcdefgh", wantErr: nil},
		{name: "valid all uppercase", alias: "ABCDEFGH", wantErr: nil},
		{name: "valid all digits", alias: "12345678", wantErr: nil},
		{name: "valid mixed case and digits", alias: "AbC123xY", wantErr: nil},
		{name: "valid exactly 32 characters", alias: "A1b2C3d4E5f6G7h8I9j0K1l2M3n4O5p6", wantErr: nil},
		{name: "empty alias", alias: "", wantErr: ErrInvalidAliasLength},
		{name: "alias exceeds 32 characters", alias: "A1b2C3d4E5f6G7h8I9j0K1l2M3n4O5p6Q", wantErr: ErrInvalidAliasLength},
		{name: "alias with hyphen", alias: "abc-123", wantErr: ErrInvalidAlias},
		{name: "alias with underscore", alias: "abc_123", wantErr: ErrInvalidAlias},
		{name: "alias with space", alias: "abc 123", wantErr: ErrInvalidAlias},
		{name: "alias with special characters", alias: "abc@123", wantErr: ErrInvalidAlias},
		{name: "alias with unicode characters", alias: "abcñ123", wantErr: ErrInvalidAlias},
		{name: "alias with slash", alias: "abc/123", wantErr: ErrInvalidAlias},
		{name: "alias with plus sign", alias: "abc+123", wantErr: ErrInvalidAlias},
		{name: "alias with newline", alias: "abc\n123", wantErr: ErrInvalidAlias},
		{name: "alias with only special characters", alias: "!@#$%^", wantErr: ErrInvalidAlias},
		{name: "alias with leading space", alias: " abc123", wantErr: ErrInvalidAlias},
		{name: "alias with trailing space", alias: "abc123 ", wantErr: ErrInvalidAlias},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := checkValidAlias(tt.alias)
			if !errors.Is(err, tt.wantErr) {
				t.Errorf("wanted = %v, got = %v", tt.wantErr, err)
			}
		})
	}
}

func TestSanitizeURL(t *testing.T) {
	// ============================================================
	// TEST CASES ARE GENERATED BY ChatGPT
	// ============================================================
	tests := []struct {
		name         string
		url          string
		wantErr      error
		wantParseErr bool
	}{
		// ============================================================
		// VALID URLs
		// ============================================================

		{
			name:    "basic http",
			url:     "http://example.com",
			wantErr: nil,
		},
		{
			name:    "basic https",
			url:     "https://example.com",
			wantErr: nil,
		},
		{
			name:    "subdomain",
			url:     "https://www.example.com",
			wantErr: nil,
		},
		{
			name:    "deep subdomain",
			url:     "https://api.v1.example.com",
			wantErr: nil,
		},
		{
			name:    "path",
			url:     "https://example.com/path/to/resource",
			wantErr: nil,
		},
		{
			name:    "path with trailing slash",
			url:     "https://example.com/",
			wantErr: nil,
		},
		{
			name:    "query",
			url:     "https://example.com?foo=bar",
			wantErr: nil,
		},
		{
			name:    "multiple query parameters",
			url:     "https://example.com?foo=bar&baz=qux",
			wantErr: nil,
		},
		{
			name:    "fragment",
			url:     "https://example.com#section",
			wantErr: nil,
		},
		{
			name:    "path query fragment",
			url:     "https://example.com/path?foo=bar#section",
			wantErr: nil,
		},
		{
			name:    "port",
			url:     "https://example.com:8080",
			wantErr: nil,
		},
		{
			name:    "http port",
			url:     "http://example.com:80",
			wantErr: nil,
		},
		{
			name:    "https port",
			url:     "https://example.com:443",
			wantErr: nil,
		},
		{
			name:    "high port",
			url:     "https://example.com:65535",
			wantErr: nil,
		},
		{
			name:    "username",
			url:     "https://user@example.com",
			wantErr: nil,
		},
		{
			name:    "username password",
			url:     "https://user:password@example.com",
			wantErr: nil,
		},
		{
			name:    "encoded path",
			url:     "https://example.com/hello%20world",
			wantErr: nil,
		},
		{
			name:    "localhost",
			url:     "http://localhost",
			wantErr: nil,
		},
		{
			name:    "localhost port",
			url:     "http://localhost:8080",
			wantErr: nil,
		},
		{
			name:    "IPv4 address",
			url:     "http://127.0.0.1",
			wantErr: nil,
		},
		{
			name:    "IPv4 with port",
			url:     "http://192.168.1.1:8080",
			wantErr: nil,
		},
		{
			name:    "IPv6 address",
			url:     "http://[::1]",
			wantErr: nil,
		},
		{
			name:    "IPv6 with port",
			url:     "http://[::1]:8080",
			wantErr: nil,
		},
		{
			name:    "long path",
			url:     "https://example.com/" + strings.Repeat("a", 1000),
			wantErr: nil,
		},
		{
			name:    "2048 characters exactly",
			url:     "https://example.com/" + strings.Repeat("a", 2028),
			wantErr: nil,
		},
		{
			name:    "uppercase HTTP",
			url:     "HTTP://example.com",
			wantErr: nil,
		},
		{
			name:    "uppercase HTTPS",
			url:     "HTTPS://example.com",
			wantErr: nil,
		},

		// ============================================================
		// INVALID LENGTH
		// ============================================================

		{
			name:    "empty string",
			url:     "",
			wantErr: ErrInvalidURLLength,
		},
		{
			name:    "2049 characters",
			url:     "https://example.com/" + strings.Repeat("a", 2029),
			wantErr: ErrInvalidURLLength,
		},
		{
			name:    "very long URL",
			url:     "https://example.com/" + strings.Repeat("a", 10000),
			wantErr: ErrInvalidURLLength,
		},

		// ============================================================
		// INVALID SCHEME
		// ============================================================

		{
			name:    "ftp scheme",
			url:     "ftp://example.com",
			wantErr: ErrInvalidScheme,
		},
		{
			name:    "ftps scheme",
			url:     "ftps://example.com",
			wantErr: ErrInvalidScheme,
		},
		{
			name:    "ws scheme",
			url:     "ws://example.com",
			wantErr: ErrInvalidScheme,
		},
		{
			name:    "wss scheme",
			url:     "wss://example.com",
			wantErr: ErrInvalidScheme,
		},
		{
			name:    "file scheme",
			url:     "file:///tmp/file.txt",
			wantErr: ErrInvalidScheme,
		},
		{
			name:    "ssh scheme",
			url:     "ssh://example.com",
			wantErr: ErrInvalidScheme,
		},
		{
			name:    "mailto scheme",
			url:     "mailto:user@example.com",
			wantErr: ErrInvalidScheme,
		},
		{
			name:    "javascript scheme",
			url:     "javascript:alert(1)",
			wantErr: ErrInvalidScheme,
		},
		{
			name:    "invalid scheme typo",
			url:     "htp://example.com",
			wantErr: ErrInvalidScheme,
		},
		{
			name:    "missing scheme",
			url:     "example.com",
			wantErr: ErrInvalidScheme,
		},
		{
			name:    "protocol-relative URL",
			url:     "//example.com",
			wantErr: ErrInvalidScheme,
		},

		// ============================================================
		// MISSING HOST
		// ============================================================

		{
			name:    "http with nothing",
			url:     "http://",
			wantErr: ErrMissingHost,
		},
		{
			name:    "https with nothing",
			url:     "https://",
			wantErr: ErrMissingHost,
		},
		{
			name:    "http with path only",
			url:     "http:///path",
			wantErr: ErrMissingHost,
		},
		{
			name:    "https with path only",
			url:     "https:///path",
			wantErr: ErrMissingHost,
		},
		{
			name:    "http with query only",
			url:     "http://?foo=bar",
			wantErr: ErrMissingHost,
		},
		{
			name:    "https with query only",
			url:     "https://?foo=bar",
			wantErr: ErrMissingHost,
		},
		{
			name:    "http with fragment only",
			url:     "http://#section",
			wantErr: ErrMissingHost,
		},
		{
			name:    "https with fragment only",
			url:     "https://#section",
			wantErr: ErrMissingHost,
		},
		{
			name:    "http with port but no host",
			url:     "http://:8080",
			wantErr: ErrMissingHost,
		},
		{
			name:    "https with port but no host",
			url:     "https://:443",
			wantErr: ErrMissingHost,
		},

		// ============================================================
		// INVALID HOST
		// ============================================================

		{
			name:    "DOMAIN exactly",
			url:     "https://" + DOMAIN,
			wantErr: ErrInvalidHost,
		},
		{
			name:    "DOMAIN with trailing slash",
			url:     "https://" + DOMAIN + "/",
			wantErr: ErrInvalidHost,
		},
		{
			name:    "DOMAIN with path",
			url:     "https://" + DOMAIN + "/some/path",
			wantErr: ErrInvalidHost,
		},
		{
			name:    "DOMAIN with query",
			url:     "https://" + DOMAIN + "?foo=bar",
			wantErr: ErrInvalidHost,
		},
		{
			name:    "DOMAIN with fragment",
			url:     "https://" + DOMAIN + "#section",
			wantErr: ErrInvalidHost,
		},
		{
			name:    "DOMAIN with port",
			url:     "https://" + DOMAIN + ":8080",
			wantErr: ErrInvalidHost,
		},
		{
			name:    "DOMAIN using http",
			url:     "http://" + DOMAIN,
			wantErr: ErrInvalidHost,
		},
		{
			name:    "DOMAIN uppercase",
			url:     "https://" + strings.ToUpper(DOMAIN),
			wantErr: ErrInvalidHost,
		},
		{
			name:    "DOMAIN mixed case",
			url:     "https://" + strings.ToUpper(DOMAIN[0:1]) + strings.ToLower(DOMAIN[1:2]+DOMAIN[2:]),
			wantErr: ErrInvalidHost,
		},
		{
			name:    "DOMAIN with username",
			url:     "https://user@" + DOMAIN,
			wantErr: ErrInvalidHost,
		},
		{
			name:    "DOMAIN with username password",
			url:     "https://user:password@" + DOMAIN,
			wantErr: ErrInvalidHost,
		},

		// These should NOT be rejected because they are different hosts.
		{
			name:    "DOMAIN as subdomain",
			url:     "https://sub." + DOMAIN,
			wantErr: nil,
		},
		{
			name:    "DOMAIN as prefix",
			url:     "https://" + DOMAIN + ".example.com",
			wantErr: nil,
		},
		{
			name:    "DOMAIN as suffix",
			url:     "https://example" + DOMAIN,
			wantErr: nil,
		},

		// ============================================================
		// URL PARSING ERRORS
		// ============================================================

		{
			name:         "invalid IPv6",
			url:          "http://[::1",
			wantParseErr: true,
		},
		{
			name:         "invalid IPv6 bracket",
			url:          "http://[example.com",
			wantParseErr: true,
		},
		{
			name:         "invalid percent encoding",
			url:          "http://example.com/%zz",
			wantParseErr: true,
		},
		{
			name:         "invalid percent encoding path",
			url:          "https://example.com/%",
			wantParseErr: true,
		},
		{
			name:         "invalid control character",
			url:          "https://example.com/\x7f",
			wantParseErr: true,
		},
		{
			name:         "invalid host character",
			url:          "https://exa mple.com",
			wantParseErr: true,
		},
		{
			name:         "invalid port",
			url:          "https://example.com:abc",
			wantParseErr: true,
		},
		{
			name:         "invalid port characters",
			url:          "https://example.com:80abc",
			wantParseErr: true,
		},
		{
			name:         "invalid port negative",
			url:          "https://example.com:-1",
			wantParseErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := sanitizeURL(tt.url)
			if tt.wantErr != nil && !errors.Is(err, tt.wantErr) {
				t.Errorf("error = %v, wanted = %v", err, tt.wantErr)
			}
			if tt.wantParseErr && err == nil {
				t.Errorf("wanted parse error but got nil")
			}
			if err != nil && got != "" {
				t.Errorf("expected empty URL while error != nil, got %v", got)
			}
		})
	}
}
